import Foundation

enum RuntimeStrings {
    static func value(for key: String) -> String? {
        let language = Bundle.main.preferredLocalizations.first ?? Locale.current.language.languageCode?.identifier ?? "en"
        let table = translations[language] ?? translations[String(language.prefix(2))] ?? translations["en"]!
        return table[key] ?? translations["en"]?[key]
    }

    private static let translations: [String: [String: String]] = [
        "en": [
            "editor.subtitle": "OpenAI-compatible endpoint",
            "bridge.auto": "Auto Bridge",
            "bridge.auto_help": "Automatically use the local Responses bridge when a provider only supports Chat Completions.",
            "bridge.test_ready_title": "Ready via Auto Bridge",
            "bridge.test_ready_message": "The API key and model work. This provider uses Chat Completions, so Codex will be routed through the local Responses bridge automatically.",
            "bridge.off_title": "Chat Completions detected",
            "bridge.off_message": "The endpoint works, but Auto Bridge is off. Turn it on to use this provider with Codex.",
            "bridge.direct_ready": "Native Responses",
            "bridge.route_ready": "Auto Bridge",
            "menu.open": "Open Codex Provider Switcher",
            "menu.active": "Active",
            "menu.openai": "OpenAI (Official)",
            "menu.bridge_active": "Bridge active",
            "menu.direct_active": "Direct connection",
            "menu.settings": "Settings…",
            "menu.quit": "Quit",
            "menu.providers": "Providers",
            "menu.switching": "Switching…",
            "editor.save_failed": "Could not save this provider.",
            "editor.name_generated": "A name will be generated automatically if left blank.",
            "settings.bridge": "Bridge",
            "settings.bridge_detail": "Auto Bridge is enabled by default. Native Responses providers connect directly; Chat-Completions-only providers are routed through localhost.",
            "bridge.keep_running": "Keep this app running while a bridged provider is active. You can close the main window; the menu bar item stays available."
        ],
        "zh-Hans": [
            "editor.subtitle": "兼容 OpenAI 协议的接口",
            "bridge.auto": "自动桥接",
            "bridge.auto_help": "当接口只支持 Chat Completions 时，自动通过本地 Responses Bridge 提供给 Codex。",
            "bridge.test_ready_title": "可通过自动桥接使用",
            "bridge.test_ready_message": "API Key 和模型调用正常。该接口使用 Chat Completions，切换时会自动通过本地 Responses Bridge 提供给 Codex。",
            "bridge.off_title": "检测到 Chat Completions",
            "bridge.off_message": "接口调用正常，但自动桥接已关闭。开启自动桥接后即可用于 Codex。",
            "bridge.direct_ready": "原生 Responses",
            "bridge.route_ready": "自动桥接",
            "menu.open": "打开 Codex Provider Switcher",
            "menu.active": "当前使用",
            "menu.openai": "OpenAI（官方）",
            "menu.bridge_active": "桥接运行中",
            "menu.direct_active": "接口直连",
            "menu.settings": "设置…",
            "menu.quit": "退出",
            "menu.providers": "接口",
            "menu.switching": "正在切换…",
            "editor.save_failed": "无法保存该接口。",
            "editor.name_generated": "名称留空时会自动生成。",
            "settings.bridge": "桥接",
            "settings.bridge_detail": "自动桥接默认开启。原生 Responses 接口直接连接；仅支持 Chat Completions 的接口自动通过本地桥接。",
            "bridge.keep_running": "使用桥接接口时请保持本 App 运行。可以关闭主窗口，菜单栏图标仍会保留。"
        ],
        "zh-Hant": [
            "editor.subtitle": "相容 OpenAI 協定的介面",
            "bridge.auto": "自動橋接",
            "bridge.auto_help": "當介面只支援 Chat Completions 時，自動透過本機 Responses Bridge 提供給 Codex。",
            "bridge.test_ready_title": "可透過自動橋接使用",
            "bridge.test_ready_message": "API Key 與模型皆可正常呼叫。此介面使用 Chat Completions，切換時會自動透過本機 Responses Bridge 提供給 Codex。",
            "bridge.off_title": "偵測到 Chat Completions",
            "bridge.off_message": "介面可正常呼叫，但自動橋接已關閉。開啟後即可供 Codex 使用。",
            "bridge.direct_ready": "原生 Responses",
            "bridge.route_ready": "自動橋接",
            "menu.open": "開啟 Codex Provider Switcher",
            "menu.active": "目前使用",
            "menu.openai": "OpenAI（官方）",
            "menu.bridge_active": "橋接執行中",
            "menu.direct_active": "介面直連",
            "menu.settings": "設定…",
            "menu.quit": "退出",
            "menu.providers": "介面",
            "menu.switching": "正在切換…",
            "editor.save_failed": "無法儲存此介面。",
            "editor.name_generated": "名稱留白時會自動產生。",
            "settings.bridge": "橋接",
            "settings.bridge_detail": "自動橋接預設開啟。原生 Responses 介面直接連線；僅支援 Chat Completions 的介面自動透過本機橋接。",
            "bridge.keep_running": "使用橋接介面時請保持 App 執行。可以關閉主視窗，選單列圖示仍會保留。"
        ],
        "ja": [
            "editor.subtitle": "OpenAI 互換エンドポイント",
            "bridge.auto": "自動ブリッジ",
            "bridge.auto_help": "Chat Completions のみ対応するプロバイダーをローカル Responses ブリッジ経由で Codex に接続します。",
            "bridge.test_ready_title": "自動ブリッジで使用可能",
            "bridge.test_ready_message": "API キーとモデルは正常です。このプロバイダーは Chat Completions を使用するため、切替時にローカル Responses ブリッジへ自動ルーティングします。",
            "bridge.off_title": "Chat Completions を検出",
            "bridge.off_message": "エンドポイントは正常ですが、自動ブリッジがオフです。Codex で使うにはオンにしてください。",
            "bridge.direct_ready": "Native Responses",
            "bridge.route_ready": "Auto Bridge",
            "menu.open": "Codex Provider Switcher を開く",
            "menu.active": "使用中",
            "menu.openai": "OpenAI（公式）",
            "menu.bridge_active": "ブリッジ稼働中",
            "menu.direct_active": "直接接続",
            "menu.settings": "設定…",
            "menu.quit": "終了",
            "menu.providers": "プロバイダー",
            "menu.switching": "切替中…",
            "editor.save_failed": "プロバイダーを保存できませんでした。",
            "editor.name_generated": "名前が空の場合は自動生成されます。",
            "settings.bridge": "ブリッジ",
            "settings.bridge_detail": "自動ブリッジは既定でオンです。Responses 対応プロバイダーは直接接続し、Chat Completions のみの場合はローカルブリッジを使います。",
            "bridge.keep_running": "ブリッジ利用中はこの App を終了しないでください。メインウインドウを閉じてもメニューバーから操作できます。"
        ],
        "ko": [
            "editor.subtitle": "OpenAI 호환 엔드포인트",
            "bridge.auto": "자동 브리지",
            "bridge.auto_help": "Chat Completions만 지원하는 공급자를 로컬 Responses 브리지를 통해 Codex에 연결합니다.",
            "bridge.test_ready_title": "자동 브리지로 사용 가능",
            "bridge.test_ready_message": "API Key와 모델이 정상입니다. 이 공급자는 Chat Completions를 사용하므로 전환 시 로컬 Responses 브리지로 자동 연결됩니다.",
            "bridge.off_title": "Chat Completions 감지됨",
            "bridge.off_message": "엔드포인트는 정상이나 자동 브리지가 꺼져 있습니다. Codex에서 사용하려면 켜세요.",
            "bridge.direct_ready": "Native Responses",
            "bridge.route_ready": "Auto Bridge",
            "menu.open": "Codex Provider Switcher 열기",
            "menu.active": "현재 사용",
            "menu.openai": "OpenAI(공식)",
            "menu.bridge_active": "브리지 실행 중",
            "menu.direct_active": "직접 연결",
            "menu.settings": "설정…",
            "menu.quit": "종료",
            "menu.providers": "공급자",
            "menu.switching": "전환 중…",
            "editor.save_failed": "공급자를 저장할 수 없습니다.",
            "editor.name_generated": "이름을 비워 두면 자동으로 생성됩니다.",
            "settings.bridge": "브리지",
            "settings.bridge_detail": "자동 브리지는 기본으로 켜져 있습니다. Responses 공급자는 직접 연결하고 Chat Completions만 지원하면 로컬 브리지를 사용합니다.",
            "bridge.keep_running": "브리지 공급자를 사용하는 동안 앱을 실행 상태로 유지하세요. 메인 창은 닫아도 메뉴 막대에서 계속 사용할 수 있습니다."
        ],
        "es": [
            "editor.subtitle": "Endpoint compatible con OpenAI",
            "bridge.auto": "Puente automático",
            "bridge.auto_help": "Usa automáticamente el puente local Responses cuando un proveedor solo admite Chat Completions.",
            "bridge.test_ready_title": "Listo mediante puente automático",
            "bridge.test_ready_message": "La API Key y el modelo funcionan. Como este proveedor usa Chat Completions, Codex se conectará automáticamente mediante el puente local Responses.",
            "bridge.off_title": "Chat Completions detectado",
            "bridge.off_message": "El endpoint funciona, pero el puente automático está desactivado. Actívalo para usar este proveedor con Codex.",
            "bridge.direct_ready": "Responses nativo",
            "bridge.route_ready": "Puente automático",
            "menu.open": "Abrir Codex Provider Switcher",
            "menu.active": "Activo",
            "menu.openai": "OpenAI (oficial)",
            "menu.bridge_active": "Puente activo",
            "menu.direct_active": "Conexión directa",
            "menu.settings": "Ajustes…",
            "menu.quit": "Salir",
            "menu.providers": "Proveedores",
            "menu.switching": "Cambiando…",
            "editor.save_failed": "No se pudo guardar el proveedor.",
            "editor.name_generated": "Si se deja vacío, el nombre se generará automáticamente.",
            "settings.bridge": "Puente",
            "settings.bridge_detail": "El puente automático está activado por defecto. Los proveedores Responses se conectan directamente y los de Chat Completions usan el puente local.",
            "bridge.keep_running": "Mantén esta app abierta mientras uses un proveedor con puente. Puedes cerrar la ventana principal; el icono de la barra de menús seguirá disponible."
        ]
    ]
}
